version: "3.9"
services:
  redis:
    build:
      context: .
      dockerfile: redis/Dockerfile
    ports:
      - "6379:6379"
  fastapi:
    build: .
    ports:
      - "8000:8000"
    command: ./start-reload.sh
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
