#version: '3.7'
#
#services:
#  db:
#    container_name: "db"
#    image: postgres:14.1-alpine
#    restart: always
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - custom
#  apiproject:
#    container_name: apiproject
#    image: apiproject
#    environment:
#      REAL_DATABASE_URL: "postgresql+asyncpg://postgres:postgres@db:5432/postgres"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    networks:
#      - custom
#networks:
#  custom:
#    driver: bridge